name: Guides v3 converter
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '12'
          cache: 'npm'
          cache-dependency-path: '**/npm-shrinkwrap.json'
      - run: npm install

      - name: echo nodejs information
        run: |
          echo "node version $(node -v) running"
          echo "npm version $(npm -v) running"

      - name: lint
        run: |
          npm run lint
